# Generated by Django 3.0.6 on 2020-05-19 16:26

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0002_auto_20200519_1925'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pro',
            new_name='Profile',
        ),
    ]
